---
abstract: 'Date manipulation routines'
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
build_requires:
  Module::Build: '0.21'
  Test::Inter: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.21'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Date-Manip
provides:
  Date::Manip:
    file: lib/Date/Manip.pm
    version: '6.51'
  Date::Manip::Base:
    file: lib/Date/Manip/Base.pm
    version: '6.51'
  Date::Manip::DM5:
    file: lib/Date/Manip/DM5.pm
    version: '6.51'
  Date::Manip::DM5abbrevs:
    file: lib/Date/Manip/DM5abbrevs.pm
    version: '6.51'
  Date::Manip::DM6:
    file: lib/Date/Manip/DM6.pm
    version: '6.51'
  Date::Manip::Date:
    file: lib/Date/Manip/Date.pm
    version: '6.51'
  Date::Manip::Delta:
    file: lib/Date/Manip/Delta.pm
    version: '6.51'
  Date::Manip::Lang::catalan:
    file: lib/Date/Manip/Lang/catalan.pm
    version: '6.51'
  Date::Manip::Lang::danish:
    file: lib/Date/Manip/Lang/danish.pm
    version: '6.51'
  Date::Manip::Lang::dutch:
    file: lib/Date/Manip/Lang/dutch.pm
    version: '6.51'
  Date::Manip::Lang::english:
    file: lib/Date/Manip/Lang/english.pm
    version: '6.51'
  Date::Manip::Lang::finnish:
    file: lib/Date/Manip/Lang/finnish.pm
    version: '6.51'
  Date::Manip::Lang::french:
    file: lib/Date/Manip/Lang/french.pm
    version: '6.51'
  Date::Manip::Lang::german:
    file: lib/Date/Manip/Lang/german.pm
    version: '6.51'
  Date::Manip::Lang::index:
    file: lib/Date/Manip/Lang/index.pm
    version: '6.51'
  Date::Manip::Lang::italian:
    file: lib/Date/Manip/Lang/italian.pm
    version: '6.51'
  Date::Manip::Lang::norwegian:
    file: lib/Date/Manip/Lang/norwegian.pm
    version: '6.51'
  Date::Manip::Lang::polish:
    file: lib/Date/Manip/Lang/polish.pm
    version: '6.51'
  Date::Manip::Lang::portugue:
    file: lib/Date/Manip/Lang/portugue.pm
    version: '6.51'
  Date::Manip::Lang::romanian:
    file: lib/Date/Manip/Lang/romanian.pm
    version: '6.51'
  Date::Manip::Lang::russian:
    file: lib/Date/Manip/Lang/russian.pm
    version: '6.51'
  Date::Manip::Lang::spanish:
    file: lib/Date/Manip/Lang/spanish.pm
    version: '6.51'
  Date::Manip::Lang::swedish:
    file: lib/Date/Manip/Lang/swedish.pm
    version: '6.51'
  Date::Manip::Lang::turkish:
    file: lib/Date/Manip/Lang/turkish.pm
    version: '6.51'
  Date::Manip::Obj:
    file: lib/Date/Manip/Obj.pm
    version: '6.51'
  Date::Manip::Recur:
    file: lib/Date/Manip/Recur.pm
    version: '6.51'
  Date::Manip::TZ:
    file: lib/Date/Manip/TZ.pm
    version: '6.51'
  Date::Manip::TZ_Base:
    file: lib/Date/Manip/TZ_Base.pm
    version: '6.51'
  Date::Manip::TZdata:
    file: lib/Date/Manip/TZdata.pm
    version: '6.51'
  Date::Manip::Zones:
    file: lib/Date/Manip/Zones.pm
    version: '6.51'
requires:
  Carp: '0'
  Data::Dumper: '0'
  Encode: '0'
  IO::File: '0'
  Storable: '0'
  perl: '5.006'
  utf8: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/SBECK-github/Date-Manip
version: '6.51'
