#!/bin/sh

# Usage:
#   runtests [-T] [prefix]
#
# Runs all tests (or those starting with prefix),optionally in taint mode

TI_MODE='inter'
export TI_MODE

TI_QUIET=2
export TI_QUIET

if [ "$RELEASE_TESTING" != "0" ]; then
   RELEASE_TESTING=1
   export RELEASE_TESTING
fi

if [ "$DATE_MANIP_TEST_DM5" != "0" ]; then
   DATE_MANIP_TEST_DM5=1
   export DATE_MANIP_TEST_DM5
fi

if [ "$1" = "-T" ]; then
   taint="-T -I../lib -I."
   shift
else
   taint=
fi

subset=$1

for test in ${subset}*.t ;do
  perl $taint ./$test
done
